### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sting1999** [alliefitter/boto3_type_annotations#3]
I am unable to install boto3_type_annotations.  After running "pip install boto3_type_annotations", I get this error:

```
Collecting boto3_type_annotations
  Using cached https://files.pythonhosted.org/packages/df/ad/25fe18c82397f3b8f7cd6a558106b4e48daa54886c5fb91557e649e81f2a/boto3_type_annotations-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bd/m8pk178d4pl5hhh1n8hc77wc0000gp/T/pip-install-mWjc3Y/boto3-type-annotations/setup.py", line 3, in <module>
        with open('../README.md', 'r') as f:
    IOError: [Errno 2] No such file or directory: '../README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bd/m8pk178d4pl5hhh1n8hc77wc0000gp/T/pip-install-mWjc3Y/boto3-type-annotations/
```
Any thought on this error?  Thanks.

**Comment by alliefitter** [comment]
Reproduced the error by trying to install the package with python2 pip. Only python 3.5+ is supported. That's when the `typing` module was added. Unless you're working on an existing project, you really should be using python3. Python2 is [reaching end of life](https://pythonclock.org/) in less than a year.
